### PR TITLE
Allow passing of labels to class

### PR DESCRIPTION
**Pull request by MWDelaney**
Split "Labels" into a separate function and added an argument to pass labels to the class; updated documentation to show functionality.

### CODE REVIEW

**Comment by jjgrainger** [comment]
Thanks for this,

I'm pretty busy at the mo' but I'll take a look at this as soon as I can :)

**Comment by MWDelaney** [comment]
Hey, ave you had a chance to look at this? I also just noticed a typo in the README which I've fixed here, too.

**Comment by jjgrainger** [comment]
@MWDelaney Thanks again for this!

I've been pretty busy the last few months. I've set aside some time to look at this alongside other fixes for the project, so updates should be coming soon!

Thank you! :)

**Comment by jjgrainger** [comment]
@MWDelaney Thank you!

I've merged this in with the latest release :)

**Pull request merged**
